# Generated by Django 3.2 on 2022-12-31 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221231_2334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SKil',
            new_name='Skill',
        ),
    ]
