# Generated by Django 3.2 on 2023-01-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='profiles/default.jpeg', null=True, upload_to='profiles/'),
        ),
    ]
