# Generated by Django 3.2 on 2023-01-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='featured_image/default.jpeg', null=True, upload_to='featured_image/'),
        ),
    ]
